# Generated by Django 4.2.4 on 2023-08-22 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0004_remove_caixa_gasto_remove_caixa_lucro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celular", models.CharField(max_length=100, unique=True)),
                ("computador", models.CharField(max_length=100, unique=True)),
                ("console", models.CharField(max_length=100, unique=True)),
                (
                    "codigo_progresso",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
            ],
        ),
    ]
