# Generated by Django 4.2.4 on 2023-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0005_clienteequipamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienteequipamento",
            name="celular",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="clienteequipamento",
            name="computador",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="clienteequipamento",
            name="console",
            field=models.CharField(max_length=100),
        ),
    ]
