# Generated by Django 4.2.4 on 2023-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0008_desktop"),
    ]

    operations = [
        migrations.AddField(
            model_name="desktop",
            name="notebook",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
